architect-checklist:
  checklist_file: docs/checklists/architect-checklist.md
  required_docs:
    - architecture.md
  default_locations:
    - docs/architecture.md

frontend-architecture-checklist:
  checklist_file: docs/checklists/frontend-architecture-checklist.md
  required_docs:
    - frontend-architecture.md
  default_locations:
    - docs/frontend-architecture.md
    - docs/fe-architecture.md

pm-checklist:
  checklist_file: docs/checklists/pm-checklist.md
  required_docs:
    - prd.md
  default_locations:
    - docs/prd.md

po-master-checklist:
  checklist_file: docs/checklists/po-master-checklist.md
  required_docs:
    - prd.md
    - architecture.md
  optional_docs:
    - frontend-architecture.md
  default_locations:
    - docs/prd.md
    - docs/frontend-architecture.md
    - docs/architecture.md

story-draft-checklist:
  checklist_file: docs/checklists/story-draft-checklist.md
  required_docs:
    - story.md
  default_locations:
    - docs/stories/*.md

story-dod-checklist:
  checklist_file: docs/checklists/story-dod-checklist.md
  required_docs:
    - story.md
  default_locations:
    - docs/stories/*.md

odoo-module-qa-checklist:
  checklist_file: bmad-agent/checklists/odoo-module-qa-checklist.md
  required_docs:
    - __manifest__.py
    - models/
    - views/
    - security/ir.model.access.csv
  default_locations:
    - 17.0/addons/{module}/
    - 18.0/addons/{module}/

odoo-security-checklist:
  checklist_file: bmad-agent/checklists/odoo-security-checklist.md
  required_docs:
    - security/ir.model.access.csv
    - models/
    - controllers/
  default_locations:
    - 17.0/addons/{module}/
    - 18.0/addons/{module}/
